# Generated by Django 3.1.6 on 2021-02-26 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('cst', models.IntegerField()),
                ('gst', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('till_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('Delivered', 'Delivered')], default='Pending', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer', verbose_name='customer name')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('method', models.CharField(blank=True, choices=[('Cheque', 'Cheque'), ('Cash', 'Cash')], max_length=10)),
                ('amount', models.PositiveIntegerField(blank=True, default=0)),
                ('cheque_id', models.CharField(blank=True, max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='Cash', max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('cheque_id', models.CharField(blank=True, max_length=100)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.payment')),
            ],
            options={
                'verbose_name_plural': 'Payment Details',
            },
        ),
        migrations.CreateModel(
            name='ItemInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Payment Summary',
                'verbose_name_plural': 'Payment Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.payment',),
        ),
        migrations.CreateModel(
            name='TaxSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Tax Summary',
                'verbose_name_plural': 'Tax Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.order',),
        ),
    ]
