# Generated by Django 3.1.6 on 2021-02-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210226_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cst',
            field=models.IntegerField(verbose_name='CST(%)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='gst',
            field=models.IntegerField(verbose_name='GST(%)'),
        ),
    ]
