# Generated by Django 3.1.6 on 2021-02-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210226_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Amount(₹)'),
        ),
    ]
