# Generated by Django 3.1.6 on 2021-02-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210226_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cheque_id',
            new_name='cheque_no',
        ),
        migrations.RenameField(
            model_name='paymentdetail',
            old_name='cheque_id',
            new_name='cheque_no',
        ),
    ]
