# Generated by Django 3.1.6 on 2021-02-27 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210226_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
