# Generated by Django 3.1.6 on 2021-05-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210516_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminst',
            name='by_hour',
            field=models.BooleanField(default=False),
        ),
    ]
