# Generated by Django 3.1.6 on 2021-02-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_paymentdetail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Complete', max_length=10),
        ),
    ]
