# Generated by Django 3.1.6 on 2021-05-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_iteminst_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminst',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], default='Incomplete', max_length=15),
        ),
    ]
