# Generated by Django 3.1.6 on 2021-05-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_iteminst_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminst',
            name='cst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='iteminst',
            name='gst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='iteminst',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
