# Generated by Django 3.1.6 on 2021-02-28 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
