# Generated by Django 3.1.6 on 2021-05-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210525_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminst',
            name='item_total',
            field=models.FloatField(default=0),
        ),
    ]
