# Generated by Django 3.1.6 on 2021-05-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_iteminst_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminst',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
