# Generated by Django 3.1.6 on 2021-02-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='available',
            field=models.IntegerField(default=0),
        ),
    ]
