# Generated by Django 3.1.6 on 2021-05-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_iteminst_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='gst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
