# Generated by Django 3.1.6 on 2021-02-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_inventory_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='available',
            new_name='occupied',
        ),
    ]
