# Generated by Django 3.1.6 on 2021-02-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210228_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity',
            new_name='available',
        ),
    ]
