# Generated by Django 3.1.6 on 2021-02-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210228_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='available',
            field=models.IntegerField(default=0),
        ),
    ]
