# Generated by Django 3.2.3 on 2021-05-30 06:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210529_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminst',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 18, 30, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='iteminst',
            name='till_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 18, 30, tzinfo=utc)),
        ),
    ]
