# Generated by Django 3.1.6 on 2021-02-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210228_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rented',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.item',),
        ),
    ]
