# Generated by Django 3.2.3 on 2021-06-06 04:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210530_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminst',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 5, 18, 30, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='iteminst',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.item'),
        ),
        migrations.AlterField(
            model_name='iteminst',
            name='till_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 5, 18, 30, tzinfo=utc)),
        ),
    ]
