# Generated by Django 3.1.6 on 2021-02-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210228_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.IntegerField(default=0),
        ),
    ]
