# Generated by Django 3.1.6 on 2021-02-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_item_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='available',
        ),
    ]
