# Generated by Django 3.2.3 on 2021-06-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
