# Generated by Django 3.1.6 on 2021-03-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_item_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminst',
            name='last_value',
            field=models.IntegerField(default=0),
        ),
    ]
