# Generated by Django 3.1.6 on 2021-03-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_iteminst_last_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cst',
            field=models.PositiveIntegerField(verbose_name='CST(%)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='gst',
            field=models.PositiveIntegerField(verbose_name='GST(%)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price(₹)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rented',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='iteminst',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
