# Generated by Django 3.1.7 on 2021-03-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210301_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Fulfilled', 'Fulfilled')], default='Pending', max_length=10),
        ),
    ]
